<?php

return [
    [
        'name' => 'template_pages',
        'type' => 'hidden',
        'value' => 'manifest.json,pages.json,common/request/config.js,common/wxApi.js,pages/user/user.vue',
    ],
    [
        'name' => '__APP_NAME__',
        'is_replace' => 1,
        'title' => '应用名称',
        'type' => 'string',
        'content' => [],
        'value' => '眼鸽',
        'rule' => '',
        'tip' => '例如：某某商城',
        'extend' => '',
    ],
    3 => [
        'name' => '__H5_ROUTE_MODE__',
        'title' => 'H5路由模式',
        'type' => 'select',
        'frontend' => 1,
        'is_replace' => 1,
        'content' => [
            'hash' => 'hash',
            'history' => 'history',
        ],
        'value' => 'hash',
        'rule' => '',
        'tip' => '',
        'extend' => '',
    ],
    [
        'name' => '__H5_BASE_PATH__',
        'title' => 'H5运行的基础路径',
        'type' => 'string',
        'is_replace' => 1,
        'content' => [],
        'value' => '/h5/',
        'rule' => '',
        'tip' => '例如/h5/,代表在域名的/h5/目录下部署运行',
        'extend' => '',
    ],
    [
        'name' => '__DOMAIN__',
        'title' => 'H5部署域名',
        'type' => 'string',
        'is_replace' => 1,
        'content' => [],
        'value' => 'http://localhost',
        'rule' => '',
        'tip' => '例如：https://www.site.com',
        'extend' => '',
    ],
    [
        'name' => '__COPYRIGHT__',
        'title' => '版权信息',
        'type' => 'string',
        'is_replace' => 1,
        'content' => [],
        'value' => '汕头东晟互娱文化有限公司版权所有',
        'rule' => '',
        'tip' => '',
        'extend' => '',
    ],
    [
        'title' => '分类模式',
        'name' => 'cat_mode',
        'type' => 'select',
        'frontend' => 1,
        'content' => [
            1 => '二级分类',
            '三级分类',
        ],
        'value' => '1',
        'rule' => '',
        'tip' => '',
        'extend' => '',
    ],
    [
        'title' => '物流查询',
        'name' => 'express_open',
        'type' => 'radio',
        'frontend' => 1,
        'content' => [
            '关闭',
            '开启',
        ],
        'value' => '0',
        'rule' => '',
        'tip' => '',
        'extend' => '',
    ],
    [
        'title' => '物流接口',
        'name' => 'express_api',
        'type' => 'string',
        'content' => [],
        'value' => '\\addons\\kdniao\\library\\Kd',
        'rule' => '',
        'tip' => '',
        'extend' => '',
    ],
    [
        'title' => 'CDN地址',
        'name' => 'cdnurl',
        'type' => 'string',
        'frontend' => 1,
        'content' => [],
        'value' => 'http://localhost',
        'rule' => '',
        'tip' => '',
        'extend' => '',
    ],
];
